// <auto-generated />
using System;
using IekaSmartClass.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IekaSmartClass.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228230209_AddStazhTablesAndRoleSeeds")]
    partial class AddStazhTablesAndRoleSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CpdHoursCompleted")
                        .HasColumnType("int");

                    b.Property<int>("CpdHoursRequired")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberRegistryNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasscodeHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "admin@ieka.al",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "System",
                            MemberRegistryNumber = "admin001",
                            PasscodeHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "blerina.gashi@ieka.al",
                            FirstName = "Blerina",
                            IsActive = true,
                            LastName = "Gashi",
                            MemberRegistryNumber = "LEKT01",
                            PasscodeHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            Phone = "+355691234567",
                            Role = "Lecturer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CpdHoursCompleted = 4,
                            CpdHoursRequired = 20,
                            Email = "artan.hoxha@ieka.al",
                            FirstName = "Artan",
                            IsActive = true,
                            LastName = "Hoxha",
                            MemberRegistryNumber = "IEKA-2045",
                            PasscodeHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            Phone = "+355692345678",
                            Role = "Member"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "dritan.shehi@ieka.al",
                            FirstName = "Dritan",
                            IsActive = true,
                            LastName = "Shehi",
                            MemberRegistryNumber = "MENT01",
                            PasscodeHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            Phone = "+355693456789",
                            Role = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "sonila.krasniqi@ieka.al",
                            FirstName = "Sonila",
                            IsActive = true,
                            LastName = "Krasniqi",
                            MemberRegistryNumber = "STU001",
                            PasscodeHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            Phone = "+355694567890",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventItemId");

                    b.ToTable("EventDates");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CpdHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<string>("WebinarLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DateId");

                    b.HasIndex("EventItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Stazhet");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StazhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StazhId");

                    b.ToTable("StazhDates");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StazhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StazhId");

                    b.ToTable("StazhDocuments");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.SystemConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDate", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Dates")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Participant", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventDate", "EventDate")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Participants")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDate");

                    b.Navigation("EventItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDate", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.Stazh", "Stazh")
                        .WithMany("Dates")
                        .HasForeignKey("StazhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stazh");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDocument", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.Stazh", "Stazh")
                        .WithMany("Documents")
                        .HasForeignKey("StazhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stazh");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventItem", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
