// <auto-generated />
using System;
using IekaSmartClass.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IekaSmartClass.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303232649_FixMissingYearlyPaymentPaidYearOnAspNetUsers")]
    partial class FixMissingYearlyPaymentPaidYearOnAspNetUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpdHoursCompleted")
                        .HasColumnType("int");

                    b.Property<int>("CpdHoursRequired")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPendingConfirmation")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LoginOtpChallengeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginOtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LoginOtpExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberRegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasscodeHash");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("YearlyPaymentPaidYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberRegistryNumber")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4d9988dc-5fb0-4a7d-bba8-22358f345c14",
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "admin@ieka.al",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsActive = true,
                            IsPendingConfirmation = false,
                            LastName = "System",
                            LockoutEnabled = false,
                            MemberRegistryNumber = "admin001",
                            NormalizedEmail = "ADMIN@IEKA.AL",
                            NormalizedUserName = "ADMIN@IEKA.AL",
                            PasswordHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "40f80465-f307-489e-91c1-5f770887ce37",
                            TwoFactorEnabled = false,
                            UserName = "admin@ieka.al"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d12a8c6-1605-4d2d-86bc-4e082b5d9917",
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "blerina.gashi@ieka.al",
                            EmailConfirmed = true,
                            FirstName = "Blerina",
                            IsActive = true,
                            IsPendingConfirmation = false,
                            LastName = "Gashi",
                            LockoutEnabled = false,
                            MemberRegistryNumber = "LEKT01",
                            NormalizedEmail = "BLERINA.GASHI@IEKA.AL",
                            NormalizedUserName = "BLERINA.GASHI@IEKA.AL",
                            PasswordHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            PhoneNumber = "+355691234567",
                            PhoneNumberConfirmed = false,
                            Role = "Lecturer",
                            SecurityStamp = "dc22936a-9e96-4706-b657-6ca2545480ef",
                            TwoFactorEnabled = false,
                            UserName = "blerina.gashi@ieka.al"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eae76cc9-f949-4028-9dc6-4164ac4d35bc",
                            CpdHoursCompleted = 4,
                            CpdHoursRequired = 20,
                            Email = "artan.hoxha@ieka.al",
                            EmailConfirmed = true,
                            FirstName = "Artan",
                            IsActive = true,
                            IsPendingConfirmation = false,
                            LastName = "Hoxha",
                            LockoutEnabled = false,
                            MemberRegistryNumber = "IEKA-2045",
                            NormalizedEmail = "ARTAN.HOXHA@IEKA.AL",
                            NormalizedUserName = "ARTAN.HOXHA@IEKA.AL",
                            PasswordHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            PhoneNumber = "+355692345678",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "d8b377ab-b0e1-4dd1-95a5-05ac76ede2f0",
                            TwoFactorEnabled = false,
                            UserName = "artan.hoxha@ieka.al"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50c578ef-d1ad-4e21-b00c-211fd4a48c20",
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "dritan.shehi@ieka.al",
                            EmailConfirmed = true,
                            FirstName = "Dritan",
                            IsActive = true,
                            IsPendingConfirmation = false,
                            LastName = "Shehi",
                            LockoutEnabled = false,
                            MemberRegistryNumber = "MENT01",
                            NormalizedEmail = "DRITAN.SHEHI@IEKA.AL",
                            NormalizedUserName = "DRITAN.SHEHI@IEKA.AL",
                            PasswordHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            PhoneNumber = "+355693456789",
                            PhoneNumberConfirmed = false,
                            Role = "Mentor",
                            SecurityStamp = "602efbc1-b231-445b-9394-a1944652f4b9",
                            TwoFactorEnabled = false,
                            UserName = "dritan.shehi@ieka.al"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a15781b-f818-4fc3-88f7-e74ec87966d8",
                            CpdHoursCompleted = 0,
                            CpdHoursRequired = 0,
                            Email = "sonila.krasniqi@ieka.al",
                            EmailConfirmed = true,
                            FirstName = "Sonila",
                            IsActive = true,
                            IsPendingConfirmation = false,
                            LastName = "Krasniqi",
                            LockoutEnabled = false,
                            MemberRegistryNumber = "STU001",
                            NormalizedEmail = "SONILA.KRASNIQI@IEKA.AL",
                            NormalizedUserName = "SONILA.KRASNIQI@IEKA.AL",
                            PasswordHash = "AQAAAAIAAYagAAAAED6a5t1RPIxnU0U+Jv7wZVV4GLlHAOtc+p0g0I75+Lfym7OOEZijLRgrubjefapC7g==",
                            PhoneNumber = "+355694567890",
                            PhoneNumberConfirmed = false,
                            Role = "Student",
                            SecurityStamp = "d4cfb051-5fe4-471b-b163-c6c18d5bc206",
                            TwoFactorEnabled = false,
                            UserName = "sonila.krasniqi@ieka.al"
                        });
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventItemId");

                    b.ToTable("EventDates");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventItemId");

                    b.ToTable("EventDocuments");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LecturerComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerRating")
                        .HasColumnType("int");

                    b.Property<string>("SessionComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Suggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventItemId");

                    b.ToTable("EventFeedbacks");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CpdHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackQuestionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerIdsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessionCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<string>("WebinarLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DateId");

                    b.HasIndex("EventItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Stazhet");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StazhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StazhId");

                    b.ToTable("StazhDates");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StazhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StazhId");

                    b.ToTable("StazhDocuments");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.SystemConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDate", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Dates")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventDocument", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Documents")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventFeedback", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventItem");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Participant", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventDate", "EventDate")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.EventItem", "EventItem")
                        .WithMany("Participants")
                        .HasForeignKey("EventItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDate");

                    b.Navigation("EventItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDate", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.Stazh", "Stazh")
                        .WithMany("Dates")
                        .HasForeignKey("StazhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stazh");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.StazhDocument", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.Stazh", "Stazh")
                        .WithMany("Documents")
                        .HasForeignKey("StazhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stazh");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("IekaSmartClass.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.EventItem", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Documents");

                    b.Navigation("Feedbacks");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("IekaSmartClass.Api.Data.Entities.Stazh", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
