"use client"

import { useState } from "react"
import { useEvents } from "@/lib/events-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import type { EventDate, FeedbackQuestion } from "@/lib/data"
import { Plus, X, CalendarPlus, Trash2, Star, MessageSquare, CheckCircle2, Zap } from "lucide-react"

interface CreateEventFormProps {
  onClose: () => void
}

const DEFAULT_SURVEY: { question: string; type: "text" | "rating" | "multiple-choice"; options: string[] }[] = [
  { question: "Cilësia e përmbajtjes (1–5)", type: "rating", options: [] },
  { question: "Qartësia e ligjëratës (1–5)", type: "rating", options: [] },
  { question: "Relevanca praktike e modulit", type: "multiple-choice", options: ["Shumë e lartë", "E lartë", "Mesatare", "E ulët"] },
  { question: "A do ta rekomandoni këtë modul?", type: "multiple-choice", options: ["Po, definitivisht", "Ndoshta", "Jo"] },
  { question: "Komente dhe sugjerime", type: "text", options: [] },
]

export function CreateEventForm({ onClose }: CreateEventFormProps) {
  const { addEvent, users } = useEvents()

  const lecturers = users.filter((u) => u.role === "Lecturer")

  const [name, setName] = useState("")
  const [place, setPlace] = useState("Salla e Trajnimeve IEKA, Tiranë")
  const [topicInput, setTopicInput] = useState("")
  const [topics, setTopics] = useState<string[]>([])
  const [sessionCapacity, setSessionCapacity] = useState("45")
  const [totalSessions, setTotalSessions] = useState("5")
  const [cpdHours, setCpdHours] = useState("4")
  const [webinarLink, setWebinarLink] = useState("")
  const [price, setPrice] = useState("0")
  const [lecturerIds, setLecturerIds] = useState<string[]>([])
  const [dates, setDates] = useState<{ date: string; time: string; location: string }[]>([{ date: "", time: "09:00 – 13:00", location: "" }])
  const [questions, setQuestions] = useState<
    { id: string; question: string; type: "text" | "rating" | "multiple-choice"; options: string[] }[]
  >([])
  const [questionsExpanded, setQuestionsExpanded] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})

  // Auto-generate session dates: from first date, add 7 days per session
  function handleAutoGenerateDates() {
    if (!dates[0]?.date) return
    const base = new Date(dates[0].date)
    const numSessions = Math.min(Number(totalSessions) || 5, 10)
    const generated = Array.from({ length: numSessions }, (_, i) => {
      const d = new Date(base)
      d.setDate(d.getDate() + i * 7)
      return {
        date: d.toISOString().split("T")[0],
        time: dates[i]?.time || "09:00 – 13:00",
        location: dates[i]?.location || "",
      }
    })
    setDates(generated)
  }

  function handleLoadDefaultSurvey() {
    setQuestions(DEFAULT_SURVEY.map((q) => ({ ...q, id: crypto.randomUUID() })))
    setQuestionsExpanded(true)
  }

  function addTopic() {
    const trimmed = topicInput.trim()
    if (trimmed && !topics.includes(trimmed)) { setTopics((p) => [...p, trimmed]); setTopicInput("") }
  }

  function addDate() { setDates((p) => [...p, { date: "", time: "09:00 – 13:00", location: "" }]) }
  function removeDate(i: number) { setDates((p) => p.filter((_, j) => j !== i)) }
  function updateDate(i: number, field: "date" | "time" | "location", value: string) {
    setDates((p) => {
      const updated = p.map((d, j) => j === i ? { ...d, [field]: value } : d)
      // Auto-generate weekly sessions when the first date is picked and there's only 1 entry
      if (i === 0 && field === "date" && value && updated.length === 1) {
        const base = new Date(value)
        const numSessions = Math.min(Number(totalSessions) || 5, 10)
        return Array.from({ length: numSessions }, (_, k) => {
          const d = new Date(base)
          d.setDate(d.getDate() + k * 7)
          return {
            date: d.toISOString().split("T")[0],
            time: "09:00 – 13:00",  // each session gets its own editable time
            location: updated[0]?.location || "",
          }
        })
      }
      return updated
    })
  }

  function addQuestion() {
    setQuestions((p) => [...p, { id: crypto.randomUUID(), question: "", type: "text", options: [] }])
    setQuestionsExpanded(true)
  }
  function removeQuestion(id: string) { setQuestions((p) => p.filter((q) => q.id !== id)) }
  function updateQuestion(id: string, field: "question" | "type", value: string) {
    setQuestions((p) => p.map((q) => {
      if (q.id !== id) return q
      if (field === "type") return { ...q, type: value as "text" | "rating" | "multiple-choice", options: value === "multiple-choice" ? (q.options.length > 0 ? q.options : [""]) : [] }
      return { ...q, [field]: value }
    }))
  }
  function addOption(qId: string) { setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: [...q.options, ""] } : q)) }
  function updateOption(qId: string, oi: number, value: string) {
    setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: q.options.map((o, j) => j === oi ? value : o) } : q))
  }
  function removeOption(qId: string, oi: number) {
    setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: q.options.filter((_, j) => j !== oi) } : q))
  }

  function validate(): boolean {
    const errs: Record<string, string> = {}
    if (!name.trim()) errs.name = "Emri i modulit është i detyrueshëm"
    if (!place.trim()) errs.place = "Vendi është i detyrueshëm"
    if (topics.length === 0) errs.topics = "Shtoni të paktën një temë"
    if (!sessionCapacity || Number(sessionCapacity) <= 0) errs.sessionCapacity = "Kapaciteti duhet të jetë > 0"
    if (!totalSessions || Number(totalSessions) <= 0) errs.totalSessions = "Numri sesioneve duhet të jetë > 0"
    if (dates.length === 0 || !dates[0].date) errs.dates = "Shtoni të paktën një datë"
    dates.forEach((d, i) => { if (!d.date) errs[`date-${i}`] = "Data është e detyrueshme" })
    setErrors(errs)
    return Object.keys(errs).length === 0
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!validate()) return
    const cap = Number(sessionCapacity)
    const sess = Number(totalSessions)

    const eventDates: EventDate[] = dates.map((d, i) => ({
      id: `new-${i}`,
      date: d.date,
      time: d.time,
      location: d.location.trim() || undefined,
      maxParticipants: cap,
      currentParticipants: 0,
    }))

    const feedbackQuestions: FeedbackQuestion[] = questions
      .filter((q) => q.question.trim())
      .map((q) => ({
        id: q.id,
        question: q.question,
        type: q.type,
        options: q.type === "multiple-choice" ? q.options.filter(Boolean) : undefined,
      }))

    try {
      await addEvent({
        name: name.trim(),
        place: place.trim(),
        topics,
        sessionCapacity: cap,
        totalSessions: sess,
        dates: eventDates,
        feedbackQuestions,
        quizQuestions: [],
        status: "upcoming",
        cpdHours: Number(cpdHours) || 4,
        webinarLink: webinarLink.trim() || undefined,
        price: Number(price) || 0,
        lecturerIds
      })
      onClose()
    } catch (e) {
      setErrors({ name: "Failed to create event" })
    }
  }

  const computed = Number(sessionCapacity) * Number(totalSessions)

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-foreground/40 px-4 py-8 backdrop-blur-sm">
      <div className="w-full max-w-2xl rounded-xl border border-border bg-card shadow-lg">
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div>
            <h2 className="text-lg font-semibold text-foreground">Krijo Modul CPD të Ri</h2>
            <p className="text-xs text-muted-foreground mt-0.5">Moduli do të krijohet me sesione të shumta (p.sh. 5 × 45 vende)</p>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Mbyll formularin">
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="flex flex-col gap-5 p-6">
          {/* Name */}
          <div className="flex flex-col gap-2">
            <Label htmlFor="event-name">Emri i Modulit CPD *</Label>
            <Input id="event-name" placeholder="p.sh. Azhurnimet IFRS 2026" value={name} onChange={(e) => setName(e.target.value)} />
            {errors.name && <p className="text-xs text-destructive">{errors.name}</p>}
          </div>

          {/* Place & Webinar Link */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="flex flex-col gap-2 relative">
              <Label htmlFor="place">Vendi *</Label>
              <Input
                id="place"
                value={place}
                onChange={(e) => setPlace(e.target.value)}
                placeholder="Adresa OSE linku..."
                className={`transition-colors ${errors.place ? "border-destructive focus-visible:ring-destructive" : "focus-visible:ring-primary"}`}
              />
              {errors.place && <p className="text-xs text-destructive absolute -bottom-5 left-0">{errors.place}</p>}
            </div>

            <div className="flex flex-col gap-2">
              <Label htmlFor="webinarLink">Linku i Webinarit (Opsionale)</Label>
              <Input
                id="webinarLink"
                type="url"
                value={webinarLink}
                onChange={(e) => setWebinarLink(e.target.value)}
                placeholder="https://zoom.us/j/..."
              />
            </div>

            <div className="flex flex-col gap-2 sm:col-span-2">
              <Label>Cakto Lektor (Opsionale)</Label>
              <div className="flex flex-wrap gap-2 rounded-lg border border-border p-3 min-h-[50px] bg-background">
                {lecturers.map(l => {
                  const isSelected = lecturerIds.includes(l.id)
                  return (
                    <div
                      key={l.id}
                      onClick={() => setLecturerIds(p => isSelected ? p.filter(x => x !== l.id) : [...p, l.id])}
                      className={`cursor-pointer border px-3 py-1 text-sm rounded-full transition-colors ${isSelected ? "bg-primary text-primary-foreground border-primary" : "bg-muted text-muted-foreground border-transparent hover:bg-muted/80"
                        }`}
                    >
                      {l.firstName} {l.lastName}
                    </div>
                  )
                })}
                {lecturers.length === 0 && <p className="text-sm text-muted-foreground">Nuk ka lektorë në sistem.</p>}
              </div>
            </div>
          </div>

          {/* Topics */}
          <div className="flex flex-col gap-2">
            <Label>Temat e Modulit *</Label>
            <div className="flex gap-2">
              <Input placeholder="Shtoni temë dhe shtypni Enter..." value={topicInput}
                onChange={(e) => setTopicInput(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addTopic() } }} />
              <Button type="button" variant="secondary" onClick={addTopic} size="sm"><Plus className="h-4 w-4" /></Button>
            </div>
            {topics.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {topics.map((t) => (
                  <span key={t} className="inline-flex items-center gap-1.5 rounded-md bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                    {t}
                    <button type="button" onClick={() => setTopics((p) => p.filter((x) => x !== t))} className="rounded-full hover:bg-primary/20" aria-label={`Hiq ${t}`}>
                      <X className="h-3 w-3" />
                    </button>
                  </span>
                ))}
              </div>
            )}
            {errors.topics && <p className="text-xs text-destructive">{errors.topics}</p>}
          </div>

          {/* Capacity + Sessions + CPD + Price */}
          <div className="grid grid-cols-3 gap-3 rounded-lg border border-border bg-muted/30 p-4">
            <div className="flex flex-col gap-2">
              <Label htmlFor="session-cap">Vende/Sesion *</Label>
              <Input id="session-cap" type="number" min="1" value={sessionCapacity} onChange={(e) => setSessionCapacity(e.target.value)} />
              {errors.sessionCapacity && <p className="text-xs text-destructive">{errors.sessionCapacity}</p>}
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="total-sess">Nr. Sesionesh *</Label>
              <Input id="total-sess" type="number" min="1" value={totalSessions} onChange={(e) => setTotalSessions(e.target.value)} />
              {errors.totalSessions && <p className="text-xs text-destructive">{errors.totalSessions}</p>}
            </div>
            <div className="flex flex-col gap-2">
              <Label htmlFor="cpd">Orë CPD</Label>
              <Input
                id="cpd"
                type="number"
                min="0"
                value={cpdHours}
                onChange={(e) => setCpdHours(e.target.value)}
                placeholder="4"
              />
            </div>

            <div className="flex flex-col gap-2">
              <Label htmlFor="price">Çmimi (LEK)</Label>
              <Input
                id="price"
                type="number"
                min="0"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                placeholder="0"
              />
            </div>
            {!isNaN(computed) && computed > 0 && (
              <p className="col-span-3 text-xs text-muted-foreground">
                Kapaciteti total: <strong className="text-foreground">{computed} vende</strong> ({sessionCapacity} × {totalSessions} sesione)
              </p>
            )}
          </div>

          {/* Dates */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <Label>Datat e Sesioneve *</Label>
              <div className="flex gap-2">
                <Button type="button" variant="outline" size="sm" onClick={handleAutoGenerateDates} className="gap-1.5 text-xs" disabled={!dates[0]?.date}>
                  <Zap className="h-3.5 w-3.5" />Auto {totalSessions} sesione
                </Button>
                <Button type="button" variant="ghost" size="sm" onClick={addDate} className="gap-1.5 text-xs">
                  <CalendarPlus className="h-3.5 w-3.5" />Më shumë
                </Button>
              </div>
            </div>
            {errors.dates && <p className="text-xs text-destructive">{errors.dates}</p>}
            <div className="flex flex-col gap-2">
              {dates.map((d, i) => (
                <div key={i} className="flex items-start gap-2 rounded-lg border border-border bg-muted/20 p-3">
                  <div className="flex-1 flex flex-col gap-1">
                    <p className="text-xs text-muted-foreground">Sesioni {i + 1}</p>
                    <div className="flex gap-2">
                      <Input type="date" value={d.date} onChange={(e) => updateDate(i, "date", e.target.value)} className="text-sm flex-1" />
                      <Input type="text" value={d.time} onChange={(e) => updateDate(i, "time", e.target.value)} placeholder="09:00 – 13:00" className="text-sm w-36" />
                    </div>
                    <div className="flex gap-2">
                      <Input type="text" value={d.location} onChange={(e) => updateDate(i, "location", e.target.value)} placeholder="Lokacioni specifik (opsionale)" className="text-sm flex-1 mt-1" />
                    </div>
                    {errors[`date-${i}`] && <p className="text-xs text-destructive">{errors[`date-${i}`]}</p>}
                  </div>
                  {dates.length > 1 && (
                    <button type="button" onClick={() => removeDate(i)}
                      className="mt-5 rounded-lg p-1 text-muted-foreground hover:bg-muted hover:text-destructive" aria-label="Hiq datën">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Feedback Questions */}
          <div className="rounded-xl border border-border overflow-hidden">
            <div onClick={() => setQuestionsExpanded(!questionsExpanded)}
              className="flex w-full items-center justify-between p-4 hover:bg-muted/30 transition-colors cursor-pointer">
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10">
                  <MessageSquare className="h-4 w-4 text-primary" />
                </div>
                <div className="text-left">
                  <p className="text-sm font-semibold text-foreground">Pyetësor i Feedback-ut</p>
                  <p className="text-xs text-muted-foreground">
                    {questions.length} pyetje — dërgohet pas modulit
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                {questions.length === 0 && (
                  <button type="button" onClick={(e) => { e.stopPropagation(); handleLoadDefaultSurvey() }}
                    className="text-xs rounded-md border border-border px-2.5 py-1 text-muted-foreground hover:text-foreground hover:bg-muted transition-colors">
                    Ngarko Surveyin Standard
                  </button>
                )}
              </div>
            </div>

            {questionsExpanded && (
              <div className="border-t border-border p-4">
                {questions.length === 0 ? (
                  <div className="flex flex-col items-center gap-3 py-6 text-center">
                    <p className="text-xs text-muted-foreground">Asnjë pyetje akoma</p>
                    <div className="flex gap-2">
                      <Button type="button" size="sm" variant="outline" onClick={handleLoadDefaultSurvey} className="gap-1.5">
                        <Zap className="h-3.5 w-3.5" /> Surveyin Standard
                      </Button>
                      <Button type="button" size="sm" onClick={addQuestion} className="gap-1.5">
                        <Plus className="h-3.5 w-3.5" /> Shto Pyetje
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col gap-3">
                    {questions.map((q, idx) => (
                      <div key={q.id} className="group rounded-lg border border-border bg-muted/20 hover:border-primary/30 transition-all">
                        <div className="flex items-center gap-2 border-b border-border/50 px-3 py-2.5">
                          <span className="flex h-5 w-5 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">{idx + 1}</span>
                          <div className="flex gap-1.5 flex-1">
                            {(["text", "rating", "multiple-choice"] as const).map((type) => (
                              <button key={type} type="button" onClick={() => updateQuestion(q.id, "type", type)}
                                className={`flex items-center gap-1 rounded-md px-2 py-1 text-[10px] font-medium transition-all ${q.type === type ? "bg-primary/10 text-primary border border-primary/20" : "text-muted-foreground hover:text-foreground border border-transparent"}`}>
                                {type === "rating" ? <Star className="h-3 w-3" /> : type === "multiple-choice" ? <CheckCircle2 className="h-3 w-3" /> : <MessageSquare className="h-3 w-3" />}
                                {type === "text" ? "Tekst" : type === "rating" ? "Vlerësim" : "Zgjedhje"}
                              </button>
                            ))}
                          </div>
                          <button type="button" onClick={() => removeQuestion(q.id)}
                            className="rounded-lg p-1 text-muted-foreground opacity-0 group-hover:opacity-100 hover:text-destructive transition-all" aria-label="Fshi pyetjen">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                        <div className="p-3 flex flex-col gap-3">
                          <Input value={q.question} onChange={(e) => updateQuestion(q.id, "question", e.target.value)} placeholder="Shkruani pyetjen..." className="text-sm bg-card" />
                          {q.type === "multiple-choice" && (
                            <div className="rounded-lg bg-card border border-border p-3 flex flex-col gap-2">
                              {q.options.map((opt, oi) => (
                                <div key={oi} className="flex items-center gap-2">
                                  <div className="flex h-4 w-4 items-center justify-center rounded-full border-2 border-border shrink-0" />
                                  <Input value={opt} onChange={(e) => updateOption(q.id, oi, e.target.value)} placeholder={`Opsioni ${oi + 1}`} className="h-8 flex-1 text-xs bg-muted/30" />
                                  <button type="button" onClick={() => removeOption(q.id, oi)} className="p-0.5 text-muted-foreground hover:text-destructive"><X className="h-3 w-3" /></button>
                                </div>
                              ))}
                              <Button type="button" variant="ghost" size="sm" onClick={() => addOption(q.id)} className="w-fit gap-1 text-xs">
                                <Plus className="h-3 w-3" /> Shto Opsion
                              </Button>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    <Button type="button" variant="outline" size="sm" onClick={addQuestion} className="gap-1.5 border-dashed">
                      <Plus className="h-3.5 w-3.5" /> Shto Pyetje
                    </Button>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 border-t border-border pt-4">
            <Button type="button" variant="ghost" onClick={onClose}>Anulo</Button>
            <Button type="submit">Krijo Modulin CPD</Button>
          </div>
        </form>
      </div>
    </div>
  )
}
