"use client"

import { useState } from "react"
import { useEvents } from "@/lib/events-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import type { EventDate, FeedbackQuestion } from "@/lib/data"
import { Plus, X, CalendarPlus, Trash2, Star, MessageSquare, CheckCircle2, MapPin, Navigation, ChevronDown, Search } from "lucide-react"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"

interface CreateEventFormProps {
  onClose: () => void
}

const DEFAULT_SURVEY: { question: string; type: "text" | "rating" | "multiple-choice"; options: string[] }[] = [
  { question: "Cilësia e përmbajtjes (1–5)", type: "rating", options: [] },
  { question: "Qartësia e ligjëratës (1–5)", type: "rating", options: [] },
  { question: "Relevanca praktike e modulit", type: "multiple-choice", options: ["Shumë e lartë", "E lartë", "Mesatare", "E ulët"] },
  { question: "A do ta rekomandoni këtë modul?", type: "multiple-choice", options: ["Po, definitivisht", "Ndoshta", "Jo"] },
  { question: "Komente dhe sugjerime", type: "text", options: [] },
]

export function CreateEventForm({ onClose }: CreateEventFormProps) {
  const { addEvent, users } = useEvents()

  const lecturers = users.filter((u) => u.role === "Lecturer")

  const [name, setName] = useState("")
  const [place, setPlace] = useState("Salla e Trajnimeve IEKA, Tiranë")
  const [moduleRequireLocation, setModuleRequireLocation] = useState(true)
  const [useIekaLocation, setUseIekaLocation] = useState(true)
  const [moduleGoogleMapsUrl, setModuleGoogleMapsUrl] = useState("")
  const [moduleLatitude, setModuleLatitude] = useState("")
  const [moduleLongitude, setModuleLongitude] = useState("")

  const IEKA_LAT = "41.321232"
  const IEKA_LNG = "19.825963"
  const [topicInput, setTopicInput] = useState("")
  const [topics, setTopics] = useState<string[]>([])
  const [sessionCapacity, setSessionCapacity] = useState("45")
  const [totalSessions, setTotalSessions] = useState("5")
  const [cpdHours, setCpdHours] = useState("4")

  function getDefaultTime(hours: number | string): string {
    const h = Math.max(1, Number(hours) || 4)
    const endHour = 9 + h
    const end = endHour < 24 ? `${String(endHour).padStart(2, "0")}:00` : "23:00"
    return `09:00 – ${end}`
  }

  function handleCpdHoursChange(val: string) {
    setCpdHours(val)
    const newTime = getDefaultTime(val)
    setDates((p) => p.map((d) => ({ ...d, time: newTime })))
  }
  const [price, setPrice] = useState("0")
  const [lecturerIds, setLecturerIds] = useState<string[]>([])
  const [freeTextLektor, setFreeTextLektor] = useState(false)
  const [customLektorName, setCustomLektorName] = useState("")
  const [lektorDropdownOpen, setLektorDropdownOpen] = useState(false)
  const [lektorSearch, setLektorSearch] = useState("")
  const [dates, setDates] = useState<{ date: string; time: string; location: string; useCustomLocation?: boolean; requireLocation?: boolean; latitude?: string; longitude?: string; googleMapsUrl?: string }[]>([{ date: "", time: getDefaultTime(4), location: "", useCustomLocation: false, requireLocation: false, latitude: "", longitude: "", googleMapsUrl: "" }])
  const [questions, setQuestions] = useState<
    { id: string; question: string; type: "text" | "rating" | "multiple-choice"; options: string[] }[]
  >([])
  const [questionsExpanded, setQuestionsExpanded] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})

  function applyLocationToDates(lat: string, lng: string, require: boolean) {
    setDates((p) => p.map((d) => d.useCustomLocation ? d : { ...d, latitude: lat, longitude: lng, requireLocation: require }))
  }

  function handleRequireLocationToggle() {
    const next = !moduleRequireLocation
    setModuleRequireLocation(next)
    if (next) {
      // Default to IEKA location when enabling
      const lat = useIekaLocation ? IEKA_LAT : moduleLatitude
      const lng = useIekaLocation ? IEKA_LNG : moduleLongitude
      if (lat && lng) applyLocationToDates(lat, lng, true)
    } else {
      applyLocationToDates("", "", false)
    }
  }

  function handleUseIekaLocationToggle() {
    const next = !useIekaLocation
    setUseIekaLocation(next)
    if (next) {
      setModuleGoogleMapsUrl("")
      setModuleLatitude("")
      setModuleLongitude("")
      applyLocationToDates(IEKA_LAT, IEKA_LNG, moduleRequireLocation)
    } else {
      applyLocationToDates("", "", moduleRequireLocation)
    }
  }

  function handleModuleGoogleMapsUrl(url: string) {
    setModuleGoogleMapsUrl(url)
    const match = url.match(/@(-?\d+\.?\d*),(-?\d+\.?\d*)/) || url.match(/q=(-?\d+\.?\d*),(-?\d+\.?\d*)/)
    if (match) {
      setModuleLatitude(match[1])
      setModuleLongitude(match[2])
      applyLocationToDates(match[1], match[2], moduleRequireLocation)
    }
  }
  function handleAutoGenerateDates() {
    if (!dates[0]?.date) return
    const base = new Date(dates[0].date)
    const numSessions = Math.min(Number(totalSessions) || 5, 10)
    const generated = Array.from({ length: numSessions }, (_, i) => {
      const d = new Date(base)
      d.setDate(d.getDate() + i * 7)
      return {
        date: d.toISOString().split("T")[0],
        time: dates[i]?.time || getDefaultTime(cpdHours),
        location: dates[i]?.location || "",
        useCustomLocation: dates[i]?.useCustomLocation ?? false,
        requireLocation: dates[i]?.requireLocation ?? moduleRequireLocation,
        latitude: dates[i]?.latitude || (moduleRequireLocation ? (useIekaLocation ? IEKA_LAT : moduleLatitude) : "") || "",
        longitude: dates[i]?.longitude || (moduleRequireLocation ? (useIekaLocation ? IEKA_LNG : moduleLongitude) : "") || "",
        googleMapsUrl: dates[i]?.googleMapsUrl ?? "",
      }
    })
    setDates(generated)
  }

  function handleLoadDefaultSurvey() {
    setQuestionsExpanded(true)
  }

  function addTopic() {
    const trimmed = topicInput.trim()
    if (trimmed && !topics.includes(trimmed)) { setTopics((p) => [...p, trimmed]); setTopicInput("") }
  }

  function addDate() {
    const max = Number(totalSessions) || 0
    if (max > 0 && dates.length >= max) return
    const lat = moduleRequireLocation ? (useIekaLocation ? IEKA_LAT : moduleLatitude) : ""
    const lng = moduleRequireLocation ? (useIekaLocation ? IEKA_LNG : moduleLongitude) : ""
    setDates((p) => [...p, { date: "", time: getDefaultTime(cpdHours), location: "", useCustomLocation: false, requireLocation: moduleRequireLocation, latitude: lat, longitude: lng, googleMapsUrl: "" }])
  }
  function removeDate(i: number) { setDates((p) => p.filter((_, j) => j !== i)) }
  function updateDate(i: number, field: "date" | "time" | "location", value: string) {
    setDates((p) => {
      const updated = p.map((d, j) => j === i ? { ...d, [field]: value } : d)
      // Auto-generate weekly sessions when the first date is picked and there's only 1 entry
      if (i === 0 && field === "date" && value && updated.length === 1) {
        const base = new Date(value)
        const numSessions = Math.min(Number(totalSessions) || 5, 10)
        return Array.from({ length: numSessions }, (_, k) => {
          const d = new Date(base)
          d.setDate(d.getDate() + k * 7)
          return {
            date: d.toISOString().split("T")[0],
            time: getDefaultTime(cpdHours),
            location: updated[0]?.location || "",
            useCustomLocation: updated[0]?.useCustomLocation ?? false,
            requireLocation: updated[0]?.requireLocation ?? moduleRequireLocation,
            latitude: updated[0]?.latitude || (moduleRequireLocation ? (useIekaLocation ? IEKA_LAT : moduleLatitude) : "") || "",
            longitude: updated[0]?.longitude || (moduleRequireLocation ? (useIekaLocation ? IEKA_LNG : moduleLongitude) : "") || "",
            googleMapsUrl: updated[0]?.googleMapsUrl ?? "",
          }
        })
      }
      return updated
    })
  }
  function toggleCustomLocation(i: number) {
    setDates((p) => p.map((d, j) => j === i ? { ...d, useCustomLocation: !d.useCustomLocation, location: !d.useCustomLocation ? d.location : "", requireLocation: !d.useCustomLocation ? d.requireLocation : false, latitude: !d.useCustomLocation ? d.latitude : "", longitude: !d.useCustomLocation ? d.longitude : "" } : d))
  }
  function toggleRequireLocation(i: number) {
    setDates((p) => p.map((d, j) => j === i ? { ...d, requireLocation: !d.requireLocation } : d))
  }
  function handleGoogleMapsUrl(i: number, url: string) {
    setDates((p) => p.map((d, j) => {
      if (j !== i) return d
      const updated = { ...d, googleMapsUrl: url }
      const match = url.match(/@(-?\d+\.?\d*),(-?\d+\.?\d*)/) || url.match(/q=(-?\d+\.?\d*),(-?\d+\.?\d*)/)
      if (match) {
        updated.latitude = match[1]
        updated.longitude = match[2]
      }
      return updated
    }))
  }

  function addQuestion() {
    setQuestions((p) => [...p, { id: crypto.randomUUID(), question: "", type: "text", options: [] }])
    setQuestionsExpanded(true)
  }
  function removeQuestion(id: string) { setQuestions((p) => p.filter((q) => q.id !== id)) }
  function updateQuestion(id: string, field: "question" | "type", value: string) {
    setQuestions((p) => p.map((q) => {
      if (q.id !== id) return q
      if (field === "type") return { ...q, type: value as "text" | "rating" | "multiple-choice", options: value === "multiple-choice" ? (q.options.length > 0 ? q.options : [""]) : [] }
      return { ...q, [field]: value }
    }))
  }
  function addOption(qId: string) { setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: [...q.options, ""] } : q)) }
  function updateOption(qId: string, oi: number, value: string) {
    setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: q.options.map((o, j) => j === oi ? value : o) } : q))
  }
  function removeOption(qId: string, oi: number) {
    setQuestions((p) => p.map((q) => q.id === qId ? { ...q, options: q.options.filter((_, j) => j !== oi) } : q))
  }

  function validate(): boolean {
    const errs: Record<string, string> = {}
    if (!name.trim()) errs.name = "Emri i modulit është i detyrueshëm"
    if (!place.trim()) errs.place = "Vendi është i detyrueshëm"
    if (topics.length === 0) errs.topics = "Shtoni të paktën një temë"
    if (!sessionCapacity || Number(sessionCapacity) <= 0) errs.sessionCapacity = "Kapaciteti duhet të jetë > 0"
    if (!totalSessions || Number(totalSessions) <= 0) errs.totalSessions = "Numri sesioneve duhet të jetë > 0"
    if (dates.length === 0 || !dates[0].date) errs.dates = "Shtoni të paktën një datë"
    dates.forEach((d, i) => { if (!d.date) errs[`date-${i}`] = "Data është e detyrueshme" })
    setErrors(errs)
    return Object.keys(errs).length === 0
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!validate()) return
    const cap = Number(sessionCapacity)
    const sess = Number(totalSessions)

    const eventDates: EventDate[] = dates.map((d, i) => ({
      id: `new-${i}`,
      date: d.date,
      time: d.time,
      location: d.useCustomLocation && d.location.trim() ? d.location.trim() : undefined,
      requireLocation: d.requireLocation || false,
      latitude: d.latitude ? Number(d.latitude) : undefined,
      longitude: d.longitude ? Number(d.longitude) : undefined,
      maxParticipants: cap,
      currentParticipants: 0,
    }))

    const feedbackQuestions: FeedbackQuestion[] = questions
      .filter((q) => q.question.trim())
      .map((q) => ({
        id: q.id,
        question: q.question,
        type: q.type,
        options: q.type === "multiple-choice" ? q.options.filter(Boolean) : undefined,
      }))

    try {
      await addEvent({
        name: name.trim(),
        place: place.trim(),
        topics,
        sessionCapacity: cap,
        totalSessions: sess,
        dates: eventDates,
        feedbackQuestions,
        quizQuestions: [],
        status: "upcoming",
        cpdHours: Number(cpdHours) || 4,
        price: Number(price) || 0,
        lecturerIds: freeTextLektor ? [] : lecturerIds,
        lecturerName: freeTextLektor ? customLektorName.trim() || undefined : undefined,
      })
      onClose()
    } catch (e) {
      setErrors({ name: "Failed to create event" })
    }
  }

  const computed = Number(sessionCapacity) * Number(totalSessions)

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-foreground/40 px-4 py-8 backdrop-blur-sm">
      <div className="w-full max-w-2xl rounded-xl border border-border bg-card shadow-lg">
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div>
            <h2 className="text-lg font-semibold text-foreground">Krijo Modul CPD të Ri</h2>
            <p className="text-xs text-muted-foreground mt-0.5">Moduli do të krijohet me sesione të shumta (p.sh. 5 × 45 vende)</p>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Mbyll formularin">
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="flex flex-col gap-5 p-6">
          {/* Name */}
          <div className="flex flex-col gap-2">
            <Label htmlFor="event-name">Emri i Modulit CPD *</Label>
            <Input id="event-name" placeholder="p.sh. Azhurnimet IFRS 2026" value={name} onChange={(e) => setName(e.target.value)} />
            {errors.name && <p className="text-xs text-destructive">{errors.name}</p>}
          </div>

          {/* Vendi & Vendodhja */}
          <div className="rounded-xl border border-border overflow-hidden">
            <div className="flex items-center gap-2 border-b border-border bg-muted/30 px-4 py-2.5">
              <MapPin className="h-3.5 w-3.5 text-primary" />
              <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Vendi &amp; Vendodhja</span>
            </div>
            <div className="flex flex-col gap-4 p-4">
              {/* Place */}
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="place">Adresa fizike *</Label>
                <Input
                  id="place"
                  value={place}
                  onChange={(e) => setPlace(e.target.value)}
                  placeholder="p.sh. Salla e Trajnimeve IEKA, Tiranë"
                  className={`transition-colors ${errors.place ? "border-destructive focus-visible:ring-destructive" : "focus-visible:ring-primary"}`}
                />
                {errors.place && <p className="text-xs text-destructive">{errors.place}</p>}
              </div>

              <div className="h-px bg-border" />

              {/* GPS + IEKA on same row */}
              <div className="flex items-center gap-2">
                <label className="flex items-center gap-2.5 flex-1 h-10 px-3 rounded-md border border-input bg-background cursor-pointer select-none hover:bg-muted/40 transition-colors">
                  <input
                    type="checkbox"
                    checked={moduleRequireLocation}
                    onChange={handleRequireLocationToggle}
                    className="h-4 w-4 accent-primary shrink-0"
                  />
                  <span className="text-sm font-medium">Kërko GPS për prezencën</span>
                </label>

                {moduleRequireLocation && (
                  <label className="flex items-center gap-2.5 flex-1 h-10 px-3 rounded-md border border-input bg-background cursor-pointer select-none hover:bg-muted/40 transition-colors">
                    <input
                      type="checkbox"
                      checked={useIekaLocation}
                      onChange={handleUseIekaLocationToggle}
                      className="h-4 w-4 accent-primary shrink-0"
                    />
                    <span className="text-sm font-medium">Vendodhja e IEKA</span>
                    <span className="text-xs text-muted-foreground ml-auto whitespace-nowrap">{Number(IEKA_LAT).toFixed(4)}, {Number(IEKA_LNG).toFixed(4)}</span>
                  </label>
                )}
              </div>

              {/* Maps URL field — only when GPS checked and not using IEKA */}
              {moduleRequireLocation && !useIekaLocation && (
                <div className="flex flex-col gap-1.5">
                  <div className="flex items-center gap-1.5">
                    <Navigation className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
                    <Input
                      id="mapsUrl"
                      value={moduleGoogleMapsUrl}
                      onChange={(e) => handleModuleGoogleMapsUrl(e.target.value)}
                      placeholder="Ngjisni linkun e Google Maps..."
                      className="text-sm"
                    />
                  </div>
                  {moduleLatitude && moduleLongitude ? (
                    <p className="flex items-center gap-1.5 text-xs text-green-600 pl-5">
                      <CheckCircle2 className="h-3.5 w-3.5" />
                      {Number(moduleLatitude).toFixed(5)}, {Number(moduleLongitude).toFixed(5)}
                    </p>
                  ) : (
                    <p className="text-xs text-muted-foreground pl-5">P.sh. nga Google Maps → Shpërnda → Kopjo link</p>
                  )}
                </div>
              )}

              {moduleRequireLocation && useIekaLocation && (
                <p className="flex items-center gap-1.5 text-xs text-green-600">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  GPS aktiv • Koordinatat e IEKA konfirmuara
                </p>
              )}
            </div>
          </div>

          {/* Cakto Lektor */}
          <div className="rounded-xl border border-border">
            <div className="flex items-center justify-between border-b border-border bg-muted/30 px-4 py-2.5 rounded-t-xl">
              <div className="flex items-center gap-2">
                <Star className="h-3.5 w-3.5 text-primary" />
                <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Cakto Lektor</span>
              </div>
              <label className="flex items-center gap-2 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={freeTextLektor}
                  onChange={() => { setFreeTextLektor(p => !p); setCustomLektorName(""); setLecturerIds([]) }}
                  className="h-3.5 w-3.5 accent-primary"
                />
                <span className="text-xs text-muted-foreground">Lektor i jashtëm</span>
              </label>
            </div>
            <div className="p-4 relative">
              {freeTextLektor ? (
                <div className="flex flex-col gap-1.5">
                  <Input
                    value={customLektorName}
                    onChange={(e) => setCustomLektorName(e.target.value)}
                    placeholder="p.sh. Prof. Dr. Artan Hoxha"
                  />
                  <p className="text-xs text-muted-foreground">Shkruani emrin e lektorit të jashtëm</p>
                </div>
              ) : (
                <div className="flex flex-col gap-2 relative">
                  {/* Selected tags */}
                  {lecturerIds.length > 0 && (
                    <div className="flex flex-wrap gap-1.5">
                      {lecturerIds.map(id => {
                        const l = lecturers.find(x => x.id === id)
                        if (!l) return null
                        return (
                          <span key={id} className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2.5 py-0.5 text-xs font-medium text-primary border border-primary/20">
                            {l.firstName} {l.lastName}
                            <button type="button" onClick={() => setLecturerIds(p => p.filter(x => x !== id))} className="ml-0.5 rounded-full hover:bg-primary/20 transition-colors">
                              <X className="h-2.5 w-2.5" />
                            </button>
                          </span>
                        )
                      })}
                    </div>
                  )}
                  {/* Trigger */}
                  <button
                    type="button"
                    onClick={() => setLektorDropdownOpen(p => !p)}
                    className="flex items-center justify-between w-full h-10 px-3 rounded-md border border-input bg-background text-sm hover:bg-muted/40 transition-colors"
                  >
                    <span className="text-muted-foreground">
                      {lecturerIds.length === 0 ? "Kërko dhe zgjidh lektor..." : `${lecturerIds.length} lektorë zgjedhur`}
                    </span>
                    <ChevronDown className={`h-4 w-4 text-muted-foreground transition-transform ${lektorDropdownOpen ? "rotate-180" : ""}`} />
                  </button>
                  {/* Dropdown */}
                  {lektorDropdownOpen && (
                    <>
                      <div className="fixed inset-0 z-40" onClick={() => setLektorDropdownOpen(false)} />
                      <div className="absolute top-full left-0 right-0 z-50 mt-1 rounded-md border border-border bg-popover shadow-md">
                        <Command>
                          <CommandInput
                            autoFocus
                            value={lektorSearch}
                            onValueChange={setLektorSearch}
                            placeholder="Filtro..."
                          />
                          <CommandList className="max-h-52">
                            <CommandEmpty>Nuk u gjet asnjë lektor.</CommandEmpty>
                            <CommandGroup>
                              {lecturers.map(l => {
                                const isSelected = lecturerIds.includes(l.id)
                                return (
                                  <CommandItem
                                    key={l.id}
                                    value={`${l.firstName} ${l.lastName}`}
                                    onSelect={() => {
                                      setLecturerIds(p => isSelected ? p.filter(x => x !== l.id) : [...p, l.id])
                                    }}
                                    className="flex items-center gap-2.5 cursor-pointer"
                                  >
                                    <div className={`flex h-4 w-4 shrink-0 items-center justify-center rounded border transition-colors ${isSelected ? "border-primary bg-primary" : "border-border bg-background"
                                      }`}>
                                      {isSelected && (
                                        <svg className="h-2.5 w-2.5 text-primary-foreground" fill="none" viewBox="0 0 10 10">
                                          <path d="M1.5 5l2.5 2.5 4.5-4.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                                        </svg>
                                      )}
                                    </div>
                                    <span className="text-sm">{l.firstName} {l.lastName}</span>
                                    {l.email && <span className="text-xs text-muted-foreground ml-auto">{l.email}</span>}
                                  </CommandItem>
                                )
                              })}
                            </CommandGroup>
                          </CommandList>
                        </Command>
                      </div>
                    </>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Topics */}
          <div className="flex flex-col gap-2">
            <Label>Temat e Modulit *</Label>
            <div className="flex gap-2">
              <Input placeholder="Shtoni temë dhe shtypni Enter..." value={topicInput}
                onChange={(e) => setTopicInput(e.target.value)}
                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addTopic() } }} />
              <Button type="button" variant="secondary" onClick={addTopic} size="sm"><Plus className="h-4 w-4" /></Button>
            </div>
            {topics.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {topics.map((t) => (
                  <span key={t} className="inline-flex items-center gap-1.5 rounded-md bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                    {t}
                    <button type="button" onClick={() => setTopics((p) => p.filter((x) => x !== t))} className="rounded-full hover:bg-primary/20" aria-label={`Hiq ${t}`}>
                      <X className="h-3 w-3" />
                    </button>
                  </span>
                ))}
              </div>
            )}
            {errors.topics && <p className="text-xs text-destructive">{errors.topics}</p>}
          </div>

          {/* Capacity + Sessions + CPD + Price */}
          <div className="flex flex-col gap-3 rounded-lg border border-border bg-muted/30 p-4">
            <div className="grid grid-cols-4 gap-3">
              <div className="flex flex-col gap-2">
                <Label htmlFor="session-cap">Vende/Sesion *</Label>
                <Input id="session-cap" type="number" min="1" value={sessionCapacity} onChange={(e) => setSessionCapacity(e.target.value)} />
                {errors.sessionCapacity && <p className="text-xs text-destructive">{errors.sessionCapacity}</p>}
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="total-sess">Nr. Sesionesh *</Label>
                <Input id="total-sess" type="number" min="1" value={totalSessions} onChange={(e) => setTotalSessions(e.target.value)} />
                {errors.totalSessions && <p className="text-xs text-destructive">{errors.totalSessions}</p>}
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="cpd">Orë CPD</Label>
                <Input
                  id="cpd"
                  type="number"
                  min="0"
                  value={cpdHours}
                  onChange={(e) => handleCpdHoursChange(e.target.value)}
                  placeholder="4"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="price">Çmimi (LEK)</Label>
                <Input
                  id="price"
                  type="number"
                  min="0"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  placeholder="0"
                />
              </div>
            </div>
            {!isNaN(computed) && computed > 0 && (
              <p className="text-xs text-muted-foreground">
                Kapaciteti total: <strong className="text-foreground">{computed} vende</strong> ({sessionCapacity} × {totalSessions} sesione)
              </p>
            )}
          </div>

          {/* Dates */}
          <div className="flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <Label>Datat e Sesioneve *</Label>
              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={addDate}
                  disabled={Number(totalSessions) > 0 && dates.length >= Number(totalSessions)}
                  className="gap-1.5 text-xs"
                >
                  <CalendarPlus className="h-3.5 w-3.5" />Shto Sesion
                  {Number(totalSessions) > 0 && (
                    <span className="text-muted-foreground">({dates.length}/{totalSessions})</span>
                  )}
                </Button>
              </div>
            </div>
            {errors.dates && <p className="text-xs text-destructive">{errors.dates}</p>}
            <div className="flex flex-col gap-2">
              {dates
                .map((d, i) => ({ d, i }))
                .sort((a, b) => (a.d.date && b.d.date ? a.d.date.localeCompare(b.d.date) : a.d.date ? -1 : b.d.date ? 1 : 0))
                .map(({ d, i }, displayIndex) => (
                  <div key={i} className="flex flex-col gap-2 rounded-lg border border-border bg-muted/20 p-3">
                    <div className="flex items-center gap-2">
                      <p className="text-xs text-muted-foreground shrink-0">Sesioni {displayIndex + 1}</p>
                      <div className="flex gap-2 flex-1">
                        <Input type="date" value={d.date} onChange={(e) => updateDate(i, "date", e.target.value)} className="text-sm flex-1" />
                        <Input type="text" value={d.time} onChange={(e) => updateDate(i, "time", e.target.value)} placeholder="09:00 – 13:00" className="text-sm w-36" />
                      </div>
                      <label className="flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer shrink-0 select-none">
                        <input
                          type="checkbox"
                          checked={!!d.useCustomLocation}
                          onChange={() => toggleCustomLocation(i)}
                          className="h-3.5 w-3.5 accent-primary"
                        />
                        <MapPin className="h-3 w-3" />Lokacion tjetër
                      </label>
                      {dates.length > 1 && (
                        <button type="button" onClick={() => removeDate(i)}
                          className="rounded-lg p-1 text-muted-foreground hover:bg-muted hover:text-destructive" aria-label="Hiq datën">
                          <Trash2 className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                    {d.useCustomLocation && (
                      <div className="flex flex-col gap-1.5">
                        <Input
                          value={d.location}
                          onChange={(e) => updateDate(i, "location", e.target.value)}
                          placeholder="p.sh. Salla B2, Hotel Sheraton..."
                          className="text-sm"
                        />
                        <Input
                          value={d.googleMapsUrl ?? ""}
                          onChange={(e) => handleGoogleMapsUrl(i, e.target.value)}
                          placeholder="Google Maps URL (për koordinata)"
                          className="text-sm"
                        />
                        {d.latitude && d.longitude && (
                          <p className="text-[11px] text-green-600">✓ Koordinatat u extëraktuan: {Number(d.latitude).toFixed(5)}, {Number(d.longitude).toFixed(5)}</p>
                        )}
                        <label className="flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer select-none">
                          <input
                            type="checkbox"
                            checked={!!d.requireLocation}
                            onChange={() => toggleRequireLocation(i)}
                            className="h-3.5 w-3.5 accent-primary"
                          />
                          Kërko validim vendndodhje gjatë skanimit QR
                        </label>
                      </div>
                    )}
                    {errors[`date-${i}`] && <p className="text-xs text-destructive">{errors[`date-${i}`]}</p>}
                  </div>
                ))}
            </div>
          </div>

          {/* Feedback Questions */}
          <div className="rounded-xl border border-border overflow-hidden">
            <div onClick={() => setQuestionsExpanded(!questionsExpanded)}
              className="flex w-full items-center justify-between p-4 hover:bg-muted/30 transition-colors cursor-pointer">
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10">
                  <MessageSquare className="h-4 w-4 text-primary" />
                </div>
                <div className="text-left">
                  <p className="text-sm font-semibold text-foreground">Pyetësor i Feedback-ut</p>
                  <p className="text-xs text-muted-foreground">
                    {questions.length} pyetje — dërgohet pas modulit
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={(e) => { e.stopPropagation(); addQuestion() }}
                  className="text-xs rounded-md border border-border px-2.5 py-1 text-muted-foreground hover:text-foreground hover:bg-muted transition-colors flex items-center gap-1"
                >
                  <Plus className="h-3 w-3" /> Shto Pyetje
                </button>
              </div>
            </div>

            {questionsExpanded && (
              <div className="border-t border-border p-4">
                {questions.length === 0 ? (
                  <div className="flex flex-col items-center gap-3 py-6 text-center">
                    <p className="text-xs text-muted-foreground">Asnjë pyetje akoma</p>
                    <Button type="button" size="sm" onClick={addQuestion} className="gap-1.5">
                      <Plus className="h-3.5 w-3.5" /> Shto Pyetje
                    </Button>
                  </div>
                ) : (
                  <div className="flex flex-col gap-3">
                    {questions.map((q, idx) => (
                      <div key={q.id} className="group rounded-lg border border-border bg-muted/20 hover:border-primary/30 transition-all">
                        <div className="flex items-center gap-2 border-b border-border/50 px-3 py-2.5">
                          <span className="flex h-5 w-5 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">{idx + 1}</span>
                          <div className="flex gap-1.5 flex-1">
                            {(["text", "rating", "multiple-choice"] as const).map((type) => (
                              <button key={type} type="button" onClick={() => updateQuestion(q.id, "type", type)}
                                className={`flex items-center gap-1 rounded-md px-2 py-1 text-[10px] font-medium transition-all ${q.type === type ? "bg-primary/10 text-primary border border-primary/20" : "text-muted-foreground hover:text-foreground border border-transparent"}`}>
                                {type === "rating" ? <Star className="h-3 w-3" /> : type === "multiple-choice" ? <CheckCircle2 className="h-3 w-3" /> : <MessageSquare className="h-3 w-3" />}
                                {type === "text" ? "Tekst" : type === "rating" ? "Vlerësim" : "Zgjedhje"}
                              </button>
                            ))}
                          </div>
                          <button type="button" onClick={() => removeQuestion(q.id)}
                            className="rounded-lg p-1 text-muted-foreground opacity-0 group-hover:opacity-100 hover:text-destructive transition-all" aria-label="Fshi pyetjen">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                        <div className="p-3 flex flex-col gap-3">
                          <Input value={q.question} onChange={(e) => updateQuestion(q.id, "question", e.target.value)} placeholder="Shkruani pyetjen..." className="text-sm bg-card" />
                          {q.type === "multiple-choice" && (
                            <div className="rounded-lg bg-card border border-border p-3 flex flex-col gap-2">
                              {q.options.map((opt, oi) => (
                                <div key={oi} className="flex items-center gap-2">
                                  <div className="flex h-4 w-4 items-center justify-center rounded-full border-2 border-border shrink-0" />
                                  <Input value={opt} onChange={(e) => updateOption(q.id, oi, e.target.value)} placeholder={`Opsioni ${oi + 1}`} className="h-8 flex-1 text-xs bg-muted/30" />
                                  <button type="button" onClick={() => removeOption(q.id, oi)} className="p-0.5 text-muted-foreground hover:text-destructive"><X className="h-3 w-3" /></button>
                                </div>
                              ))}
                              <Button type="button" variant="ghost" size="sm" onClick={() => addOption(q.id)} className="w-fit gap-1 text-xs">
                                <Plus className="h-3 w-3" /> Shto Opsion
                              </Button>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    <Button type="button" variant="outline" size="sm" onClick={addQuestion} className="gap-1.5 border-dashed">
                      <Plus className="h-3.5 w-3.5" /> Shto Pyetje
                    </Button>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 border-t border-border pt-4">
            <Button type="button" variant="ghost" onClick={onClose}>Anulo</Button>
            <Button
              type="submit"
              disabled={
                !name.trim() ||
                topics.length === 0 ||
                dates.length === 0 ||
                dates.some(d => !d.date)
              }
            >Krijo Modulin CPD</Button>
          </div>
        </form>
      </div>
    </div>
  )
}
