"use client"

import { useState } from "react"
import { useEvents } from "@/lib/events-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import type { EventItem } from "@/lib/data"
import { Plus, X, CalendarPlus, Trash2, Zap, MapPin } from "lucide-react"

interface EditEventFormProps {
    event: EventItem
    onClose: () => void
}

export function EditEventForm({ event, onClose }: EditEventFormProps) {
    const { updateEvent, users } = useEvents()

    const lecturers = users.filter((u) => u.role === "Lecturer")

    const [name, setName] = useState(event.name)
    const [place, setPlace] = useState(event.place)
    const [topicInput, setTopicInput] = useState("")
    const [topics, setTopics] = useState<string[]>(event.topics ?? [])
    const [sessionCapacity, setSessionCapacity] = useState(String(event.sessionCapacity))
    const [totalSessions, setTotalSessions] = useState(String(event.totalSessions))
    const [cpdHours, setCpdHours] = useState(String(event.cpdHours))
    const [webinarLink, setWebinarLink] = useState(event.webinarLink ?? "")
    const [price, setPrice] = useState(String(event.price ?? 0))
    const [lecturerIds, setLecturerIds] = useState<string[]>(event.lecturerIds ?? [])
    const [dates, setDates] = useState<{ date: string; time: string; location?: string; useCustomLocation?: boolean; requireLocation?: boolean; latitude?: string; longitude?: string; googleMapsUrl?: string }[]>(
        (event.dates ?? []).map((d) => ({
            date: d.date.split("T")[0], // strip time part if ISO
            time: d.time,
            location: d.location ?? "",
            useCustomLocation: !!d.location,
            requireLocation: d.requireLocation ?? false,
            latitude: d.latitude != null ? String(d.latitude) : "",
            longitude: d.longitude != null ? String(d.longitude) : "",
            googleMapsUrl: "",
        }))
    )
    const [errors, setErrors] = useState<Record<string, string>>({})
    const [saving, setSaving] = useState(false)

    function addTopic() {
        const t = topicInput.trim()
        if (t && !topics.includes(t)) { setTopics((p) => [...p, t]); setTopicInput("") }
    }

    function addDate() { setDates((p) => [...p, { date: "", time: "09:00 – 13:00", location: "", useCustomLocation: false, requireLocation: false, latitude: "", longitude: "", googleMapsUrl: "" }]) }
    function removeDate(i: number) { setDates((p) => p.filter((_, j) => j !== i)) }
    function updateDate(i: number, field: "date" | "time" | "location", value: string) {
        setDates((p) => p.map((d, j) => j === i ? { ...d, [field]: value } : d))
    }
    function toggleCustomLocation(i: number) {
        setDates((p) => p.map((d, j) => j === i ? { ...d, useCustomLocation: !d.useCustomLocation, location: !d.useCustomLocation ? d.location : "" } : d))
    }

    function toggleRequireLocation(i: number) {
        setDates((p) => p.map((d, j) => j === i ? { ...d, requireLocation: !d.requireLocation } : d))
    }

    function handleGoogleMapsUrl(i: number, url: string) {
        setDates((p) => p.map((d, j) => {
            if (j !== i) return d
            const updated = { ...d, googleMapsUrl: url }
            // Try to extract coordinates from Google Maps URL
            const match = url.match(/@(-?\d+\.?\d*),(-?\d+\.?\d*)/) || url.match(/q=(-?\d+\.?\d*),(-?\d+\.?\d*)/)
            if (match) {
                updated.latitude = match[1]
                updated.longitude = match[2]
            }
            return updated
        }))
    }

    function handleAutoGenerateDates() {
        if (!dates[0]?.date) return
        const base = new Date(dates[0].date)
        const numSessions = Math.min(Number(totalSessions) || 5, 10)
        const generated = Array.from({ length: numSessions }, (_, i) => {
            const d = new Date(base)
            d.setDate(d.getDate() + i * 7)
            return { date: d.toISOString().split("T")[0], time: dates[i]?.time || "09:00 – 13:00", location: dates[i]?.location ?? "", useCustomLocation: dates[i]?.useCustomLocation ?? false }
        })
        setDates(generated)
    }

    function validate(): boolean {
        const errs: Record<string, string> = {}
        if (!name.trim()) errs.name = "Emri i modulit është i detyrueshëm"
        if (!place.trim()) errs.place = "Vendi është i detyrueshëm"
        if (topics.length === 0) errs.topics = "Shtoni të paktën një temë"
        if (!sessionCapacity || Number(sessionCapacity) <= 0) errs.sessionCapacity = "Kapaciteti duhet të jetë > 0"
        if (!totalSessions || Number(totalSessions) <= 0) errs.totalSessions = "Numri sesioneve duhet të jetë > 0"
        if (dates.length === 0 || !dates[0].date) errs.dates = "Shtoni të paktën një datë"
        dates.forEach((d, i) => { if (!d.date) errs[`date-${i}`] = "Data është e detyrueshme" })
        setErrors(errs)
        return Object.keys(errs).length === 0
    }

    async function handleSubmit(e: React.FormEvent) {
        e.preventDefault()
        if (!validate()) return
        setSaving(true)
        try {
            const payload = {
                name: name.trim(),
                place: place.trim(),
                topics,
                sessionCapacity: Number(sessionCapacity),
                totalSessions: Number(totalSessions),
                cpdHours: Number(cpdHours) || 4,
                price: Number(price) || 0,
                webinarLink: webinarLink.trim() || undefined,
                lecturerIds,
                dates: dates.map((d) => ({
                    date: d.date,
                    time: d.time,
                    location: d.useCustomLocation && d.location?.trim() ? d.location.trim() : undefined,
                    requireLocation: d.requireLocation || false,
                    latitude: d.latitude ? Number(d.latitude) : undefined,
                    longitude: d.longitude ? Number(d.longitude) : undefined,
                    googleMapsUrl: d.googleMapsUrl?.trim() || undefined,
                })),
            }
            await updateEvent(event.id, payload as any)
            onClose()
        } catch {
            setErrors({ name: "Gabim gjatë ruajtjes. Provo përsëri." })
        } finally {
            setSaving(false)
        }
    }

    const computed = Number(sessionCapacity) * Number(totalSessions)

    return (
        <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-foreground/40 px-4 py-8 backdrop-blur-sm">
            <div className="w-full max-w-2xl rounded-xl border border-border bg-card shadow-lg">
                {/* Header */}
                <div className="flex items-center justify-between border-b border-border px-6 py-4">
                    <div>
                        <h2 className="text-lg font-semibold text-foreground">Modifiko Modulin CPD</h2>
                        <p className="text-xs text-muted-foreground mt-0.5 truncate max-w-xs">{event.name}</p>
                    </div>
                    <button onClick={onClose} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground">
                        <X className="h-5 w-5" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="flex flex-col gap-5 p-6">
                    {/* Name */}
                    <div className="flex flex-col gap-2">
                        <Label htmlFor="edit-name">Emri i Modulit *</Label>
                        <Input id="edit-name" value={name} onChange={(e) => setName(e.target.value)} />
                        {errors.name && <p className="text-xs text-destructive">{errors.name}</p>}
                    </div>

                    {/* Place & Webinar */}
                    <div className="grid gap-4 sm:grid-cols-2">
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-place">Vendi *</Label>
                            <Input id="edit-place" value={place} onChange={(e) => setPlace(e.target.value)} />
                            {errors.place && <p className="text-xs text-destructive">{errors.place}</p>}
                        </div>
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-webinar">Linku i Webinarit (Opsionale)</Label>
                            <Input id="edit-webinar" type="url" value={webinarLink} onChange={(e) => setWebinarLink(e.target.value)} placeholder="https://zoom.us/j/..." />
                        </div>
                        <div className="flex flex-col gap-2 sm:col-span-2">
                            <Label>Cakto Lektor (Opsionale)</Label>
                            <div className="flex flex-wrap gap-2 rounded-lg border border-border p-3 min-h-[50px] bg-background">
                                {lecturers.map(l => {
                                    const isSelected = lecturerIds.includes(l.id)
                                    return (
                                        <div
                                            key={l.id}
                                            onClick={() => setLecturerIds(p => isSelected ? p.filter(x => x !== l.id) : [...p, l.id])}
                                            className={`cursor-pointer border px-3 py-1 text-sm rounded-full transition-colors ${isSelected ? "bg-primary text-primary-foreground border-primary" : "bg-muted text-muted-foreground border-transparent hover:bg-muted/80"
                                                }`}
                                        >
                                            {l.firstName} {l.lastName}
                                        </div>
                                    )
                                })}
                                {lecturers.length === 0 && <p className="text-sm text-muted-foreground">Nuk ka lektorë në sistem.</p>}
                            </div>
                        </div>
                    </div>

                    {/* Topics */}
                    <div className="flex flex-col gap-2">
                        <Label>Temat e Modulit *</Label>
                        <div className="flex gap-2">
                            <Input placeholder="Shtoni temë dhe shtypni Enter..." value={topicInput}
                                onChange={(e) => setTopicInput(e.target.value)}
                                onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addTopic() } }} />
                            <Button type="button" variant="secondary" onClick={addTopic} size="sm"><Plus className="h-4 w-4" /></Button>
                        </div>
                        {topics.length > 0 && (
                            <div className="flex flex-wrap gap-1.5">
                                {topics.map((t) => (
                                    <span key={t} className="inline-flex items-center gap-1.5 rounded-md bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">
                                        {t}
                                        <button type="button" onClick={() => setTopics((p) => p.filter((x) => x !== t))} className="rounded-full hover:bg-primary/20">
                                            <X className="h-3 w-3" />
                                        </button>
                                    </span>
                                ))}
                            </div>
                        )}
                        {errors.topics && <p className="text-xs text-destructive">{errors.topics}</p>}
                    </div>

                    {/* Capacity + Sessions + CPD + Price */}
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 rounded-lg border border-border bg-muted/30 p-4">
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-cap">Vende/Sesion *</Label>
                            <Input id="edit-cap" type="number" min="1" value={sessionCapacity} onChange={(e) => setSessionCapacity(e.target.value)} />
                            {errors.sessionCapacity && <p className="text-xs text-destructive">{errors.sessionCapacity}</p>}
                        </div>
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-sess">Nr. Sesionesh *</Label>
                            <Input id="edit-sess" type="number" min="1" value={totalSessions} onChange={(e) => setTotalSessions(e.target.value)} />
                            {errors.totalSessions && <p className="text-xs text-destructive">{errors.totalSessions}</p>}
                        </div>
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-cpd">Orë CPD</Label>
                            <Input id="edit-cpd" type="number" min="0" value={cpdHours} onChange={(e) => setCpdHours(e.target.value)} />
                        </div>
                        <div className="flex flex-col gap-2">
                            <Label htmlFor="edit-price">Çmimi (LEK)</Label>
                            <Input id="edit-price" type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} />
                        </div>
                        {!isNaN(computed) && computed > 0 && (
                            <p className="col-span-2 sm:col-span-4 text-xs text-muted-foreground">
                                Kapaciteti total: <strong className="text-foreground">{computed} vende</strong> ({sessionCapacity} × {totalSessions} sesione)
                            </p>
                        )}
                    </div>

                    {/* Dates */}
                    <div className="flex flex-col gap-3">
                        <div className="flex items-center justify-between">
                            <Label>Datat e Sesioneve *</Label>
                            <div className="flex gap-2">
                                <Button type="button" variant="outline" size="sm" onClick={handleAutoGenerateDates} className="gap-1.5 text-xs" disabled={!dates[0]?.date}>
                                    <Zap className="h-3.5 w-3.5" />Auto {totalSessions} sesione
                                </Button>
                                <Button type="button" variant="ghost" size="sm" onClick={addDate} className="gap-1.5 text-xs">
                                    <CalendarPlus className="h-3.5 w-3.5" />Shto
                                </Button>
                            </div>
                        </div>
                        {errors.dates && <p className="text-xs text-destructive">{errors.dates}</p>}
                        <div className="flex flex-col gap-2">
                            {dates.map((d, i) => (
                                <div key={i} className="flex flex-col gap-2 rounded-lg border border-border bg-muted/20 p-3">
                                    <div className="flex items-center gap-2">
                                        <p className="text-xs text-muted-foreground shrink-0">Sesioni {i + 1}</p>
                                        <div className="flex gap-2 flex-1">
                                            <Input type="date" value={d.date} onChange={(e) => updateDate(i, "date", e.target.value)} className="text-sm flex-1" />
                                            <Input type="text" value={d.time} onChange={(e) => updateDate(i, "time", e.target.value)} placeholder="09:00 – 13:00" className="text-sm w-36" />
                                        </div>
                                        {/* Custom location toggle */}
                                        <label className="flex items-center gap-1.5 text-xs text-muted-foreground cursor-pointer shrink-0 select-none">
                                            <input
                                                type="checkbox"
                                                checked={!!d.useCustomLocation}
                                                onChange={() => toggleCustomLocation(i)}
                                                className="h-3.5 w-3.5 accent-primary"
                                            />
                                            <MapPin className="h-3 w-3" />Lokacion tjetër
                                        </label>
                                        {dates.length > 1 && (
                                            <button type="button" onClick={() => removeDate(i)}
                                                className="rounded-lg p-1 text-muted-foreground hover:bg-muted hover:text-destructive">
                                                <Trash2 className="h-4 w-4" />
                                            </button>
                                        )}
                                    </div>
                                    {d.useCustomLocation && (
                                        <Input
                                            value={d.location ?? ""}
                                            onChange={(e) => updateDate(i, "location", e.target.value)}
                                            placeholder="p.sh. Salla B2, Hotel Sheraton..."
                                            className="text-sm"
                                        />
                                    )}
                                    {errors[`date-${i}`] && <p className="text-xs text-destructive">{errors[`date-${i}`]}</p>}
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center justify-end gap-3 border-t border-border pt-4">
                        <Button type="button" variant="ghost" onClick={onClose}>Anulo</Button>
                        <Button type="submit" disabled={saving}>
                            {saving ? "Duke ruajtur..." : "Ruaj Ndryshimet"}
                        </Button>
                    </div>
                </form>
            </div>
        </div>
    )
}
