"use client"

const STUDENT_REGISTRY_PATTERN = /^ST\d{3,4}$/

function normalizeStudentInitials(firstName: string, length: number) {
  const normalized = firstName
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z]/g, "")

  return normalized.slice(0, length).padEnd(length, "X")
}

export function isAutoGeneratedStudentRegistryNumber(value: string) {
  return STUDENT_REGISTRY_PATTERN.test(value.trim().toUpperCase())
}

export function parseStudentTrackingNumber(value: string | null | undefined) {
  const normalized = (value ?? "").trim().toUpperCase()
  if (!normalized) {
    return null
  }

  const exactMatch = normalized.match(/^ST(\d{3,4})(?:-|$)/)
  if (!exactMatch) {
    return null
  }

  const parsed = Number.parseInt(exactMatch[1], 10)
  return Number.isFinite(parsed) && parsed >= 1 ? parsed : null
}

export function formatStudentTrackingCode(trackingNumber: number | null | undefined) {
  if (!Number.isFinite(trackingNumber) || !trackingNumber || trackingNumber < 1) {
    return ""
  }

  return `ST${String(trackingNumber).padStart(3, "0")}`
}

export function generateStudentRegistryNumber(_firstName: string, existingRegistryNumbers: Iterable<string>) {
  const existing = new Set(
    Array.from(existingRegistryNumbers, (value) => value.trim().toUpperCase()).filter(Boolean)
  )

  let maxSequence = 0
  for (const registry of existing) {
    const match = registry.match(/^ST(\d{3,4})$/)
    if (!match) continue

    const sequence = Number(match[1])
    if (Number.isFinite(sequence) && sequence >= 1 && sequence <= 9999) {
      maxSequence = Math.max(maxSequence, sequence)
    }
  }

  for (let offset = 1; offset <= 9999; offset++) {
    const sequence = ((maxSequence + offset - 1) % 9999) + 1
    const candidate = formatStudentTrackingCode(sequence)
    if (!existing.has(candidate)) {
      return candidate
    }
  }

  return "ST9999"
}

export function generateStudentNumber(
  registryNumber: string,
  firstName: string,
  startYear: number | null | undefined,
  endYear: number | null | undefined
) {
  const normalizedRegistryNumber = registryNumber.trim().toUpperCase()
  if (!/^ST\d{3,4}$/.test(normalizedRegistryNumber)) {
    return ""
  }

  if (!Number.isFinite(startYear) || !Number.isFinite(endYear)) {
    return ""
  }

  const initials = normalizeStudentInitials(firstName, 3)
  const startYearSuffix = String(startYear).slice(-2)
  const endYearSuffix = String(endYear).slice(-2)
  return `${normalizedRegistryNumber}-${initials}${startYearSuffix}${endYearSuffix}`
}
